---
title: "Analysis"
output: html_notebook
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
  editor_options: 
    chunk_output_type: console
  chunk_output_type: console
---

```{r}
#################################################################################################################################
# Single cell data/analysis used for:
# TIGIT inhibition and lenalidomide synergistically promote anti-myeloma immune responses after stem cell transplantation in mice
# 
# Written by: Olivia Waltner, Scott Furlan
# Data generated by: Simone Minnie, Shruti Bhise
# 
# Any questions regarding the analysis email: owaltner@fredhutch.org

#################################################################################################################################
```

```{r, include =F}
rm(list=ls())
knitr::opts_chunk$set( echo = TRUE, message=FALSE, warning=FALSE, fig.width=8 )
ROOT_DIR<-"/fh/fast/furlan_s/grp/experiments/648_Tigitdata"
DATA_DIR <- file.path(ROOT_DIR, "data")     
RES_DIR  <- file.path(ROOT_DIR,  "res")     
RMD_DIR  <- file.path(ROOT_DIR,"rmd")     
CDS_DIR <- file.path(ROOT_DIR,   "cds")
FIG_DIR <- file.path(ROOT_DIR,  "figs")

suppressPackageStartupMessages({
  library(monocle3)
  library(dplyr)
  library(Matrix)
  library(reticulate)
  library(ggplot2)
  library(pals)
  library(RColorBrewer)
  library(Seurat)
  library(ComplexHeatmap)
  library(ArchR)
  library(Biobase)
  library(stringr)
  library(viridis)
  library(Seurat)
  library(scCustomize)
  library(scRepertoire)
  library(parallel)
  library(forcats)
  library(ggalluvial)
  library(circlize)
  library(scales)
})

set.seed(1234)

##loading viewmastR package
dyn.load('/app/software/ArrayFire/3.8.1/lib64/libaf.so.3')
library(RcppArrayFire)
library(viewmastR) 

#setup python environment
Sys.setenv(RETICULATE_PYTHON = "~/.conda/envs/py3/bin/python3")

library("SeuratDisk")
library("Seurat")
library("reticulate")
use_python("~/.conda/envs/py3/bin/python3")
use_condaenv("~/.conda/envs/py3")
py_config()
```

```{r, load colors and object}
#heatmap
cds<-readRDS(file.path(CDS_DIR, "tigit_cds.rds"))
h_cols <-rev(brewer.pal(name = "RdYlBu", n = 7))

clus_cols<-c("GzmA+ Tex" ="#df76a4", "GzmB+ Teff" = "#5ca867", "Tcm"="#336eae","Tex_Cycling" = "#ea9a50",  "Tigit+ Teff" = "#d0493d","Tim-3+ Tex" = "#7b5fa2",  "Tn" = "#88c7c0", "Transitionary_effector_cells"= "#4c9096")

plot_cells(cds, color_cells_by = "cell_type")+scale_color_manual(values =clus_cols)

plot_cells(cds, color_cells_by = "sample_id", cell_size = 0.7, label_cell_groups = F)+scale_color_manual(values= ArchR::paletteDiscrete(values=levels(factor(cds$sample_id)), set = "grove", reverse = F))+facet_wrap(~sample_id)+NoAxes()
```
#cluster analysis
```{r}
tig<-monocle3_to_seurat(cds)
tig<-FindVariableFeatures(tig)
tig<-ScaleData(tig)

q<-DimPlot(tig, group.by = "cluster", label=F, reduction = "umap", split.by = "sample_id")+scale_color_manual(values = ArchR::paletteDiscrete(values = levels(factor(tig$cluster)), set = "circus", reverse=T))+NoAxes()
Idents(tig)<-"cluster"
tig_markers<-FindAllMarkers(tig, only.pos = T)
#write.csv(tig_markers, file.path(RES_DIR, "tigit_markers.csv"))
```

```{r}
top_n<-tig_markers %>% group_by(cluster) %>% slice_max(avg_log2FC, n =10)
DoHeatmap(tig, features = top_n$gene, group.by = "cluster", group.colors = ArchR::paletteDiscrete(values = levels(factor(tig$cluster)), set = "circus", reverse = T))+scale_fill_gradientn(colours = h_cols)
```

#add metadata
```{r}
tig$cell_type <- as.character(tig$cluster)
tig$cell_type[which(tig$cluster == "1")]<-"Tcm"
tig$cell_type[which(tig$cluster == "2")]<-"Tex_Cycling"
tig$cell_type[which(tig$cluster == "3")]<-"Transitionary_effector_cells"
tig$cell_type[which(tig$cluster == "4")]<-"Tn"
tig$cell_type[which(tig$cluster == "5")]<-"Tim-3+ Tex"
tig$cell_type[which(tig$cluster == "6")]<-"Tigit+ Teff"
tig$cell_type[which(tig$cluster == "7")]<-"GzmB+ Teff"
tig$cell_type[which(tig$cluster == "8")]<-"GzmA+ Tex"
```

#CELL COUNT ANALYSIS
```{r}
cds$cell_type <- tig$cell_type

df<- data.frame(table(tig$cell_type, tig$sample_id))

p<-ggplot(df, aes(fill = Var1, y=Freq, x=Var2)) + 
    geom_bar(stat = "identity",  position = "fill")+scale_fill_manual(values = c("GzmA+ Tex" ="#df76a4", "Tcm"="#336eae", "Tn" = "#88c7c0", "Transitionary_effector_cells"= "#4c9096", "Tim-3+ Tex" = "#7b5fa2", "Tex_Cycling" = "#ea9a50", "GzmB+ Teff" = "#5ca867", "Tigit+ Teff" = "#d0493d"))+theme_classic()+RotatedAxis()+NoGrid()

p
```

#DEG ANALYSIS
```{r Tcm analysis}
tcm<-tig[,tig$cell_type == "Tcm"]
Idents(tcm)<-"sample_id"
DefaultAssay(tcm)<-"RNA"
markers<-FindAllMarkers(tcm, only.pos = T)

top_n<-markers %>%dplyr::filter(!str_detect(gene ,"^Rpl")) %>%
    dplyr::filter(!str_detect(gene, "^Rps"))%>%
    dplyr::filter(!str_detect(gene, "^mt-")) %>% dplyr::filter(!str_detect(gene, "^Hist")) %>%group_by(cluster) %>% slice_max(avg_log2FC, n =40) 

avg_mat<-AverageExpression(tcm, assays = "RNA", return.seurat = T, group.by = "sample_id")
mat <- avg_mat@assays$RNA@data[unique(top_n$gene),] %>% as.matrix()
mat<- t(scale(t(mat)))
pheatmap(mat,  border_color = "gray25", main = "Tcm Top Markers Per Group")
```

```{r Tcm analysis}
mat <- avg_mat@assays$RNA@data[c("Lef1", "Ikzf2", "Slamf6", "Tcf7", "Cxcr6", "Il27ra", "Il18r1", "Ifngr1", "Bcl2", "Bach2","Ly6a", "Cxcr3"),] %>% as.matrix()
mat<- t(scale(t(mat)))
pheatmap(mat,  border_color = "black", main = "Tcm: Genes of Interest Per Group")
```

```{r Look at DE in Tex cells}
#excluding cycling Tex
tex<-tig[,tig$cell_type %in% c("GzmA+ Tex", "Tim-3+ Tex")]

Idents(tex)<-"sample_id"
DefaultAssay(tex)<-"RNA"
markers<-FindAllMarkers(tex, only.pos = T)

top_n<-markers %>%dplyr::filter(!str_detect(gene ,"^Rpl")) %>%
    dplyr::filter(!str_detect(gene, "^Rps"))%>%
    dplyr::filter(!str_detect(gene, "^mt-")) %>% dplyr::filter(!str_detect(gene, "^Hist")) %>% dplyr::filter(!str_detect(gene, "^Tr")) %>%group_by(cluster) %>% slice_max(avg_log2FC, n =5) 

avg_mat<-AverageExpression(tex, assays = "RNA", return.seurat = T, group.by = "sample_id")
mat <- avg_mat@assays$RNA@data[unique(top_n$gene),] %>% as.matrix()
mat<- t(scale(t(mat)))
pheatmap(mat,  border_color = "gray25", main = "Tex Top Marker Genes Per Group")
```
```{r Teff DEG}
table(tig$cell_type)
teff<-tig[,tig$cell_type %in% c(" GzmB+ Teff", "Tigit+ Teff",  "Transitionary_effector_cells")]

Idents(teff)<-"sample_id"
DefaultAssay(teff)<-"RNA"
markers<-FindAllMarkers(teff, only.pos = T)

top_n<-markers %>%dplyr::filter(!str_detect(gene ,"^Rpl")) %>%
    dplyr::filter(!str_detect(gene, "^Rps"))%>%
    dplyr::filter(!str_detect(gene, "^mt-")) %>% dplyr::filter(!str_detect(gene, "^Hist")) %>% dplyr::filter(!str_detect(gene, "^Tra"))%>%group_by(cluster) %>% slice_max(avg_log2FC, n =10) 

avg_mat<-AverageExpression(teff, assays = "RNA", return.seurat = T, group.by = "sample_id")
mat <- avg_mat@assays$RNA@data[unique(top_n$gene),] %>% as.matrix()
mat<- t(scale(t(mat)))
pheatmap(mat,  border_color = "gray25", main = "Teff Top Markers Per Group")
```
```{r Teff + Tex DE genes}
teff<-tig[,tig$cell_type %in% c("GzmA+ Tex", "Tim-3+ Tex", "Tex_Cycling", "Transitionary_effector_cells", "Tigit+ Teff")]

Idents(teff)<-"sample_id"
DefaultAssay(teff)<-"RNA"
markers<-FindAllMarkers(teff, only.pos = T)

top_n<-markers %>%dplyr::filter(!str_detect(gene ,"^Rpl")) %>%
    dplyr::filter(!str_detect(gene, "^Rps"))%>%
    dplyr::filter(!str_detect(gene, "^mt-")) %>% dplyr::filter(!str_detect(gene, "^Hist")) %>%group_by(cluster) %>% slice_max(avg_log2FC, n =20) 

avg_mat<-AverageExpression(teff, assays = "RNA", return.seurat = T, group.by = "sample_id")
mat <- avg_mat@assays$RNA@data[c("Prf1", "Gzmb", "Gzma", "Il10", "Ifng", "Gzmk", "Csf1", "Ccl4", "Ccl3", "Ccl5", "Fasl", "Il2"),] %>% as.matrix()
mat<- t(scale(t(mat)))
pheatmap(mat,  border_color = "gray25", main = "Teff + Tex Top Markers Per Group")
```
#Pseudotime Trajectory
```{r}
cds<-learn_graph(cds, use_partition = F)
cds<- order_cells(cds)
#picked naive cell that forks to CMs and the rest of the trajectory
plot_cells(cds, color_cells_by = "pseudotime", show_trajectory_graph = F, cell_size = 0.75)&NoAxes()
```

```{r}
functional_tex_genes <- c("Tigit", "Pdcd1", "Tox", "Tcf7", "Gzmb","Gzma", "Prf1","Ifng")
pseudo_cds <- cds[rowData(cds)$gene_short_name %in% functional_tex_genes,]
plot_genes_in_pseudotime(pseudo_cds,
                         color_cells_by="cell_type",
                         min_expr=0.5)+scale_color_manual(values = clus_cols)
```

SC REPERTOIRE ANALYSIS
#Create combined vdj, rna object
```{r}
samps<-list.files(DATA_DIR)[2:5]
folders<-list.files(file.path(DATA_DIR), full.names = T)

tcrl<-lapply(samps, function(x){
  tcr<-read.csv(file.path(DATA_DIR, x, "filtered_contig_annotations.csv"))
  tcr
})
#edit vdj files so barcodes match the cell colnames
tcrl2 <- lapply(1:length(tcrl), function(x){
  met<-tcrl[[x]]
  met$barcode<-gsub("-1", paste0("-",x), met$barcode)
  met
})

combined <- combineTCR(tcrl, samples = samps, cells ="T-AB")
combined <- combineTCR(tcrl, samples = samps, cells ="T-AB")
combined$Gp1_VDJ$barcode<-gsub(".*_", "", combined$Gp1_VDJ$barcode)
combined$Gp2_VDJ$barcode<-gsub(".*_", "", combined$Gp2_VDJ$barcode)
combined$Gp3_VDJ$barcode<-gsub(".*_", "", combined$Gp3_VDJ$barcode)
combined$Gp4_VDJ$barcode<-gsub(".*_", "", combined$Gp4_VDJ$barcode)

combined$Gp1_VDJ$barcode<-gsub("Gp1_VDJ_", "", combined$Gp1_VDJ$barcode)
combined$Gp2_VDJ$barcode<-gsub("Gp2_VDJ_", "", combined$Gp2_VDJ$barcode)
combined$Gp2_VDJ$barcode<-gsub("1", "2", combined$Gp2_VDJ$barcode)
combined$Gp3_VDJ$barcode<-gsub("Gp3_VDJ_", "", combined$Gp3_VDJ$barcode)
combined$Gp3_VDJ$barcode<-gsub("1", "3", combined$Gp3_VDJ$barcode)
combined$Gp4_VDJ$barcode<-gsub("Gp4_VDJ_", "", combined$Gp4_VDJ$barcode)
combined$Gp4_VDJ$barcode<-gsub("1", "4", combined$Gp4_VDJ$barcode)
```

#add to seurat object
```{r}
seu <- combineExpression(combined, tig, 
                  cloneCall="aa", 
                  proportion = FALSE, 
                  cloneTypes=c(Single=1, Small=5, Medium=20, Large=100, Hyperexpanded=500))
```

#Figure G overlap between experimental groups
```{r}
t<-list(combined[[4]],combined[[1]],combined[[2]],combined[[3]] )
names(t)<- c("Gp4_VDJ","Gp1_VDJ","Gp2_VDJ","Gp3_VDJ")
p<-compareClonotypes(t, numbers =10,
                    cloneCall="aa", graph = "alluvial")+ theme(axis.text.x = element_text(angle = 90))+scale_fill_manual(values = sfc(40, scramble =F))
p + aes(x = fct_inorder(p[["data"]][["Sample"]]))+geom_stratum(colour = NA)&NoGrid()
```

#Figure F Cloncal Overlap Circle Plot
```{r}
Idents(seu)<-"cell_type"
circles <- getCirclize(seu, group.by = "cell_type")
#Just assigning the normal colors to each cluster
grid.cols <- hue_pal()(length(unique(Idents(seu))))
names(grid.cols) <- levels(slot(seu, "active.ident"))

#Graphing the chord diagram
chordDiagram(circles, self.link = 1, grid.col = clus_cols)
```

#Figure E  clonality feature plot
```{r}
Idents(seu)<-"cell_type"
Idents(seu)<-"sample_id"
clonalOverlay(seu, 
              reduction = "umap", facet = "sample_id" ) + 
                 guides(color = "none")+scale_color_manual(values = paletteDiscrete(values = levels(factor(seu$sample_id)), set= "grove"))+theme_void()


slot(seu, "meta.data")$cloneType <- factor(slot(seu, "meta.data")$cloneType, 
                levels = c("Hyperexpanded (100 < X <= 500)", 
                           "Large (20 < X <= 100)", 
                            "Medium (5 < X <= 20)", 
                            "Small (1 < X <= 5)", 
                            "Single (0 < X <= 1)", NA))
cds$cloneType<-seu$cloneType
cds$cloneType<-as.character(cds$cloneType)

cds$cloneType[which(is.na(cds$cloneType))]<-"NA"
cds$cloneType

cds$cloneType<-factor(cds$cloneType, levels= rev(c("Hyperexpanded (100 < X <= 500)", "Large (20 < X <= 100)", "Medium (5 < X <= 20)", "Small (1 < X <= 5)",  "Single (0 < X <= 1)", "NA")))

plot_cells(cds, color_cells_by = "cloneType", label_cell_groups = F, cell_size = 1, show_trajectory_graph = F)+scale_color_manual(values =c("gray80",rev(brewer.spectral(n=5))))&NoAxes()
```
#prepare clonotype data frame for phils code :)
```{r}
clonotype_df<-do.call(rbind, combined)
clontype_df<-merge(clonotype_df, seu@meta.data)
```

#load excess amount of libraries
```{python libraries }
import numpy as np 
import pandas as pd

import scanpy as sc
from anndata import AnnData, concat

import matplotlib.pyplot as plt
import matplotlib_venn as venn
import seaborn as sns

from scipy import sparse, stats
from scipy.cluster import hierarchy
import gc
from itertools import product
import networkx as nx

import re
import h5py

import itertools

import statsmodels.api as sm

from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

from scipy.ndimage import gaussian_filter

import scanpy as sc
from collections import Counter, OrderedDict
from os import system
```

```{python}
df = r.clontype_df
clusters = sorted(set(df.cell_type))
all_freqs = {}
clonalities = []
dfl = []
for c in clusters:
  counts = Counter(df[df.cell_type==c].CTaa)
  top_counts = [x[1] for x in counts.most_common(10)]
  total = sum(counts.values())
  clonality = sum(x*(x-1) for x in counts.values())/((total*(total-1)))
  all_freqs[c] = Counter({x:y/total for x,y in counts.items()})
  ct = set(df[df.cell_type==c].cell_type).pop()
  print(f'clonality: {clonality:.3f} {total:4d} {ct}', top_counts)
  name = set(df[df.cell_type==c].cell_type)
  assert len(name) == 1
  dfl.append(dict(
    cluster=c,
    cell_type=name.pop(),
    simpsons_clonality=clonality,
    ))
  clonalities.append(clonality)
#pd.DataFrame(dfl).to_csv('cell_type_clonality.csv', index=False)
```

```{r}
simp<-read.csv('cell_type_clonality.csv')
simp$cell_type<-factor(simp$cell_type, levels = c("Tn", "Tcm", "GzmB+ Teff" ,"Transitionary_effector_cells","Tim-3+ Tex", "Tigit+ Teff", "GzmA+ Tex", "Tex_Cycling"  ))
ggplot(simp, aes(x = cell_type, y = simpsons_clonality, fill = cell_type)) +
  geom_bar(stat="identity")+scale_fill_manual(values = clus_cols)+theme_classic()+coord_flip()+ylab(label = "Simpson's Clonality Index")&NoLegend()
```